version: '3.7'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    image: mern-ecommerce-backend:latest  # Utiliser l'image préconstruite
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  frontend:
    image: mern-ecommerce-frontend:latest  # Utiliser l'image préconstruite
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  mongo-data:
