version: '3.7'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: mernstack_backend:latest  # Utiliser l'image préconstruite
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend
    image: mernstack_frontend:latest  # Utiliser l'image préconstruite
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  mongo-data: